spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

spring.flyway.enabled=false

# Ejecutar datos iniciales usando SQL estándar
spring.sql.init.mode=always

jwt.secret=ClaveUltraSecretaEInviolableParaLaMunicipalidad2026!
jwt.issuer=ms-auth

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

springdoc.openapi.servers[0].url=http://localhost:8080
springdoc.openapi.servers[0].description=API Gateway (Entorno Local)

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html